### ISSUE TITLE
"Copy a base64 string of the compressed config" translation bug

### ISSUE THREAD

**Issue by 5idereal** [digitalocean/nginxconfig.io#370]
## Information

[Browser Info](https://whatismybrowser.com/w/A8W8ZRD)

### Description 

The translation for "Copy a base64 string of the compressed config" will revert to English after clicked. Also, the "Copied" text isn't translatable.

### Steps to reproduce

Scroll down to Download section and "click on the Copy a base64 string of the compressed config" link.

### Expected behavior

Keep the translation after clicking.

### Screenshots

![Animation](https://user-images.githubusercontent.com/30827929/173766083-2c889279-70ca-45d8-8fbc-fcfa4cebc3f8.gif)

**Comment by MattIPv4** [comment]
Ah! Good catch. I think this logic is responsible for this:

https://github.com/digitalocean/nginxconfig.io/blob/479162576d291d2c930ba37cf322af56ff5dd307/src/nginxconfig/templates/setup.vue#L152-L175

Instead of setting `originalText` when this method is first called, we probably want to look at trying to store the original text right before the text change occurs (either in the existing success hook where it's changed to "copied", or in an earlier hook if ClipboardJS provides it).

And then the "copied" text just needs to use the translation API (`this.$t`) instead of being a plain string.

**Comment by SiderealArt** [comment]
Replacing the text makes the whole sentence weird. 
> or, **Copied**, paste it in your server's command line and execute it.

Maybe It's better to show a tooltip instead. Like this.
![image](https://user-images.githubusercontent.com/30827929/173818991-14079426-1603-415f-9ac4-fd6a4dc66850.png)

**Comment by raulsoledispa** [comment]
@MattIPv4  I'd like to work on this issue. Please, can you assign it to me?

**Comment by MattIPv4** [comment]
Sure thing :)
