### ISSUE TITLE
Add proxy timeout directives

### ISSUE THREAD

**Issue by pgilad** [digitalocean/nginxconfig.io#74]
Proxy timeouts are very helpful in closing hung connections or protecting proxy server in general. Relevant directives:

```nginx
proxy_connect_timeout       20s;
proxy_send_timeout          30s;
proxy_read_timeout          2m;
send_timeout                30s;
```

**Comment by MattIPv4** [comment]
These make sense to the three proxy related timeouts, however, they will default to the documented defaults for NGINX, so that old configurations made with the tool will not actually be affected by these being introduced, not the values provided in this issue.

- http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_connect_timeout
- http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_send_timeout
- http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_read_timeout
